ERROR > An Error Occured.
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    bot.load_extension(cog)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 651, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'commands.music ' could not be loaded.
ERROR > An Error Occured.
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    bot.load_extension(cog)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 651, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'commands.info ' could not be loaded.
ERROR > An Error Occured.
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    bot.load_extension(cog)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 651, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'commands.dms ' could not be loaded.
ERROR > An Error Occured.
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    bot.load_extension(cog)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 651, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'commands.version ' could not be loaded.
ERROR > An Error Occured.
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    bot.load_extension(cog)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 651, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'commands.mod ' could not be loaded.
ERROR > An Error Occured.
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    bot.load_extension(cog)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 651, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'commands.verify ' could not be loaded.
ERROR > An Error Occured.
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    bot.load_extension(cog)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 651, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'commands.ping ' could not be loaded.
ERROR > An Error Occured.
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    bot.load_extension(cog)
  File "/home/pi/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 651, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'commands.system ' could not be loaded.
ERROR > An Error Occured
Traceback (most recent call last):
  File "bot.py", line 37, in <module>
    with open(f'"commands-m1/{cogm2}') as rk:
FileNotFoundError: [Errno 2] No such file or directory: '"commands-m1/help.py'
ERROR > An Error Occured
Traceback (most recent call last):
  File "bot.py", line 37, in <module>
    with open(f'"commands-m1/{cogm2}') as rk:
FileNotFoundError: [Errno 2] No such file or directory: '"commands-m1/member.py'
ERROR > An Error Occured
Traceback (most recent call last):
  File "bot.py", line 37, in <module>
    with open(f'"commands-m1/{cogm2}') as rk:
FileNotFoundError: [Errno 2] No such file or directory: '"commands-m1/idpurge.py'
ERROR > An Error Occured
Traceback (most recent call last):
  File "bot.py", line 37, in <module>
    with open(f'"commands-m1/{cogm2}') as rk:
FileNotFoundError: [Errno 2] No such file or directory: '"commands-m1/stat.py'
