ERROR > An Error Occured.
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 608, in _load_from_module_spec
    setup(self)
  File "c:\Users\User\Desktop\Bot Maker Items\Bot\Bot-Python\commands\version.py", line 13, in setup
    bot.add_cog(VerCog(bot))
  File "c:\Users\User\Desktop\Bot Maker Items\Bot\Bot-Python\commands\version.py", line 6, in __init__
    self.bot = bot
NameError: name 'bot' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/User/Desktop/Bot Maker Items/Bot/Bot-Python/bot.py", line 33, in <module>
    bot.load_extension(cog)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 653, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 613, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'commands.version' raised an error: NameError: name 'bot' is not defined
